const express = require('express');
const crypto = require('crypto');
const { protect } = require('../middleware/auth');
const axios = require('axios');
const CorrelatedIncident = require('../models/CorrelatedIncident');
const Integration = require('../models/Integration');
const { ensureNarrative } = require('../services/incidentNarrativeService');

const router = express.Router();

const CORRELATION_URL = process.env.CORRELATION_ENGINE_URL || 'http://localhost:5005';

// ---------------------------------------------------------------------------
// Active cron jobs (in-memory; keyed by `userId:clusterId`)
// ---------------------------------------------------------------------------
const cronJobs = new Map();

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function buildFingerprint(cluster) {
  const parts = [
    ...(cluster.alert_names || []).sort(),
    ...(cluster.pods || []).sort(),
    ...(cluster.namespaces || []).sort(),
  ];
  return crypto.createHash('sha256').update(parts.join('|')).digest('hex').slice(0, 16);
}

function decryptConfig(integration) {
  const key = process.env.INTEGRATION_ENCRYPTION_KEY;
  const enc = integration.encryptedConfig;
  if (!key || !enc || !enc.encryptedData) return null;
  try {
    const decipher = crypto.createDecipheriv(
      'aes-256-gcm',
      Buffer.from(key, 'hex'),
      Buffer.from(enc.iv, 'hex')
    );
    decipher.setAuthTag(Buffer.from(enc.authTag, 'hex'));
    let dec = decipher.update(enc.encryptedData, 'hex', 'utf8');
    dec += decipher.final('utf8');
    return JSON.parse(dec);
  } catch (e) {
    console.error('Failed to decrypt integration config:', e.message);
    return null;
  }
}

async function createSnowIncident(userId, incident) {
  try {
    const integration = await Integration.findOne({ userId, type: 'snow', enabled: true });
    if (!integration) {
      console.log('[SNOW] No enabled ServiceNow integration found for user:', userId);
      return null;
    }

    const config = decryptConfig(integration);
    if (!config) {
      console.error('[SNOW] Failed to decrypt ServiceNow config for user:', userId);
      return null;
    }
    console.log('[SNOW] Creating incident for root cause:', incident.rootCause?.pod, 'instance:', config.instance_url);

    const auth = Buffer.from(`${config.username}:${config.password}`).toString('base64');
    const sevMap = { critical: 1, high: 2, warning: 3, medium: 3, low: 4, info: 5 };
    const topSeverity = Object.keys(incident.severities || {}).reduce((best, s) =>
      (sevMap[s] || 5) < (sevMap[best] || 5) ? s : best, 'info');

    // Prefer the written narrative — the structured dump below is already
    // appended to it — and fall back to the dump only if none was produced.
    const description = incident.description || [
      `Root Cause: ${incident.rootCause?.pod || 'Unknown'} (ns/${incident.rootCause?.namespace || 'unknown'})`,
      `Score: ${incident.rootCause?.score?.toFixed(3) || 'N/A'}`,
      `Alerts: ${incident.alertCount} across ${incident.pods?.length || 0} pods`,
      `Alert Names: ${(incident.alertNames || []).join(', ')}`,
      `Namespaces: ${(incident.namespaces || []).join(', ')}`,
      `Pods: ${(incident.pods || []).join(', ')}`,
      `Time Range: ${incident.timeRange?.start || ''} to ${incident.timeRange?.end || ''}`,
      '',
      'Evidence:',
      ...(incident.evidence || []).map(e => `  - ${e}`),
      '',
      'Causal Chain:',
      ...(incident.causalChain || []).map(c => `  ${c.role}: ${c.pod} (score: ${c.score})`),
      '',
      `Anomaly Summary: ${incident.rootCause?.anomalySummary || 'N/A'}`,
      `Occurrences: ${incident.occurrences || 1}`,
      '',
      `Generated by DevOps Copilot Correlation Engine`,
    ].join('\n');

    const body = {
      short_description: (incident.title
        || `[Correlated] ${incident.rootCause?.pod || 'Unknown'}: ${(incident.alertNames || []).slice(0, 3).join(', ')}`).slice(0, 160),
      description,
      urgency: sevMap[topSeverity] || 3,
      impact: sevMap[topSeverity] || 3,
      category: 'Software',
      subcategory: 'Application',
      assignment_group: config.assignment_group || '',
      caller_id: config.username,
    };

    const resp = await axios.post(
      `${config.instance_url}/api/now/table/incident`,
      body,
      {
        headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/json' },
        timeout: 15000,
      }
    );

    const result = resp.data?.result;
    if (result) {
      console.log('[SNOW] Incident created:', result.number, 'sys_id:', result.sys_id);
      return {
        number: result.number,           // INC0012345
        sysId: result.sys_id,
        url: `${config.instance_url}/nav_to.do?uri=incident.do?sys_id=${result.sys_id}`,
        state: 'new',
        createdAt: new Date(),
      };
    }
    console.warn('[SNOW] No result in ServiceNow response');
    return null;
  } catch (err) {
    console.error('ServiceNow incident creation failed:', err.message);
    return null;
  }
}

async function storeCorrelationResults(userId, correlationData, clusterId, cronJobId) {
  const results = [];

  // A group of one is not a correlation.
  //
  // Correlation exists to say "these N separate alerts are one problem". When a
  // cluster holds a single condition there is nothing to correlate, and raising
  // a "[Correlated] ..." incident for it both misrepresents the finding and
  // floods ServiceNow with one ticket per stray alert. Those alerts are still
  // reported — through the normal alert path — they just do not get dressed up
  // as a correlation here.
  const MIN_CONDITIONS = Number(process.env.CORRELATION_MIN_CONDITIONS || 2);
  const groups = (correlationData.clusters || []).filter((c) => {
    const conditions = c.condition_count ?? c.alert_count ?? 0;
    const distinctAlertNames = (c.alert_names || []).length;
    // Either several distinct conditions, or one condition that is clearly
    // recurring across multiple pods — both are genuinely "more than one thing".
    const correlated = conditions >= MIN_CONDITIONS || distinctAlertNames >= MIN_CONDITIONS;
    if (!correlated) {
      console.log(`[CORRELATION] skipping single-condition group (${(c.alert_names || []).join(',')}) — nothing to correlate`);
    }
    return correlated;
  });

  for (const cluster of groups) {
    const fingerprint = buildFingerprint(cluster);
    const rca = cluster.root_cause_analysis || {};

    // Check for existing active incident with same fingerprint
    const existing = await CorrelatedIncident.findOne({
      userId, fingerprint, status: { $in: ['active', 'acknowledged'] },
    });

    if (existing) {
      // Increment occurrence counter
      existing.occurrences += 1;
      existing.lastSeenAt = new Date();
      existing.alertCount = cluster.alert_count || existing.alertCount;
      existing.conditionCount = cluster.condition_count || existing.conditionCount;
      existing.occurrenceCount = cluster.occurrence_count || existing.occurrenceCount;
      if (cluster.nodes?.length) existing.nodes = cluster.nodes;
      if (cluster.workloads?.length) existing.workloads = cluster.workloads;
      if (cluster.families?.length) existing.families = cluster.families;
      existing.statuses = cluster.statuses || existing.statuses;
      existing.timeRange = {
        start: cluster.time_range?.start,
        end: cluster.time_range?.end,
        durationSeconds: cluster.time_range?.duration_seconds,
      };
      existing.anomalyDetails = cluster.anomaly_details || existing.anomalyDetails;
      existing.executionTimeMs = correlationData.execution_time_ms;
      if (rca.topology) existing.topology = rca.topology;
      if (rca.evidence) existing.evidence = rca.evidence;
      if (cronJobId) existing.cronJobId = cronJobId;

      // An incident stored before narratives existed still has none; fill it in
      // once rather than leaving older incidents permanently undescribed.
      try {
        await ensureNarrative(existing);
      } catch (e) {
        console.warn('[CORRELATION] narrative backfill failed:', e.message);
      }

      // Auto-create SNOW incident if not already created
      if (!existing.snowIncident?.number) {
        const snowResult = await createSnowIncident(userId, existing);
        if (snowResult) {
          existing.snowIncident = snowResult;
          console.log(`[SNOW] Auto-created ticket ${snowResult.number} for existing incident ${existing.fingerprint}`);
        }
      }

      await existing.save();
      results.push(existing);
    } else {
      // Create new correlated incident
      const doc = new CorrelatedIncident({
        userId,
        clusterId: clusterId || '',
        fingerprint,
        occurrences: 1,
        firstSeenAt: new Date(),
        lastSeenAt: new Date(),
        rootCause: {
          pod: rca.root_cause?.pod,
          namespace: rca.root_cause?.namespace,
          score: rca.root_cause?.score,
          anomalySummary: rca.root_cause?.anomaly_summary,
          anomalousMetrics: rca.root_cause?.anomalous_metrics || [],
        },
        alertCount: cluster.alert_count,
        conditionCount: cluster.condition_count || cluster.alert_count,
        occurrenceCount: cluster.occurrence_count || cluster.alert_count,
        alertNames: cluster.alert_names || [],
        pods: cluster.pods || [],
        nodes: cluster.nodes || [],
        workloads: cluster.workloads || [],
        families: cluster.families || [],
        namespaces: cluster.namespaces || [],
        severities: cluster.severities || {},
        statuses: cluster.statuses || {},
        causalChain: rca.causal_chain || [],
        evidence: rca.evidence || [],
        topology: rca.topology || { nodes: [], edges: [] },
        downstreamImpact: rca.downstream_impact || [],
        anomalyDetails: cluster.anomaly_details || {},
        timeRange: {
          start: cluster.time_range?.start,
          end: cluster.time_range?.end,
          durationSeconds: cluster.time_range?.duration_seconds,
        },
        executionTimeMs: correlationData.execution_time_ms,
        cronJobId: cronJobId || null,
      });

      // Write the narrative BEFORE the ticket, so ServiceNow receives the
      // readable description rather than a field dump.
      try {
        await ensureNarrative(doc);
      } catch (e) {
        console.warn('[CORRELATION] narrative failed:', e.message);
      }

      await doc.save();

      // Try to create ServiceNow incident
      const snowResult = await createSnowIncident(userId, doc);
      if (snowResult) {
        doc.snowIncident = snowResult;
        await doc.save();
      }

      results.push(doc);
    }
  }

  return results;
}

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

// POST /api/correlation/analyze — Run full correlation
router.post('/analyze', protect, async (req, res) => {
  try {
    const { clusterId, hours = 48 } = req.body;
    const userId = req.user._id.toString();
    const token = req.headers.authorization?.replace('Bearer ', '');

    const response = await axios.post(`${CORRELATION_URL}/api/correlate`, {
      userId, clusterId, token, hours: parseInt(hours),
    }, { timeout: 300000 });

    res.json(response.data);
  } catch (error) {
    console.error('Correlation proxy error:', error.message);
    if (error.response) return res.status(error.response.status).json(error.response.data);
    res.status(503).json({ success: false, error: 'Correlation engine unavailable. Ensure it is running on port 5005.' });
  }
});

// POST /api/correlation/analyze-and-store — Run correlation + store results
router.post('/analyze-and-store', protect, async (req, res) => {
  try {
    const { clusterId, hours = 48 } = req.body;
    const userId = req.user._id.toString();
    const token = req.headers.authorization?.replace('Bearer ', '');

    const response = await axios.post(`${CORRELATION_URL}/api/correlate`, {
      userId, clusterId, token, hours: parseInt(hours),
    }, { timeout: 300000 });

    const data = response.data;
    if (data.success && data.clusters?.length > 0) {
      const stored = await storeCorrelationResults(userId, data, clusterId);
      data.storedIncidents = stored.map(s => ({
        _id: s._id, fingerprint: s.fingerprint, occurrences: s.occurrences,
        snowIncident: s.snowIncident || null,
      }));
    }

    res.json(data);
  } catch (error) {
    console.error('Correlation analyze-and-store error:', error.message);
    if (error.response) return res.status(error.response.status).json(error.response.data);
    res.status(503).json({ success: false, error: 'Correlation engine unavailable.' });
  }
});

// GET /api/correlation/incidents — Get stored correlated incidents
router.get('/incidents', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const { status, limit = 50 } = req.query;
    const query = { userId };
    if (status) query.status = status;

    const incidents = await CorrelatedIncident.find(query)
      .sort({ lastSeenAt: -1 })
      .limit(parseInt(limit));

    res.json({ success: true, incidents });
  } catch (error) {
    console.error('Get incidents error:', error.message);
    res.status(500).json({ success: false, error: error.message });
  }
});

// GET /api/correlation/incidents/by-alert — Find correlated incidents matching an alert name or pod
router.get('/incidents/by-alert', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const { alertname, pod, clusterId } = req.query;
    if (!alertname && !pod) return res.status(400).json({ success: false, error: 'alertname or pod required' });

    const query = { userId };
    const orConds = [];
    if (alertname) orConds.push({ alertNames: alertname });
    if (pod) orConds.push({ pods: pod });
    if (orConds.length) query.$or = orConds;
    if (clusterId) query.clusterId = clusterId;

    const incidents = await CorrelatedIncident.find(query)
      .sort({ lastSeenAt: -1 })
      .limit(5)
      .lean();

    res.json({ success: true, incidents });
  } catch (error) {
    console.error('Get incidents by-alert error:', error.message);
    res.status(500).json({ success: false, error: error.message });
  }
});

// PATCH /api/correlation/incidents/:id — Update incident status
router.patch('/incidents/:id', protect, async (req, res) => {
  try {
    const { status } = req.body;
    const incident = await CorrelatedIncident.findOneAndUpdate(
      { _id: req.params.id, userId: req.user._id.toString() },
      { status },
      { new: true }
    );
    if (!incident) return res.status(404).json({ success: false, error: 'Not found' });
    res.json({ success: true, incident });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

const orchestrator = require('../services/incidentOrchestrator');

// POST /api/correlation/incidents/:id/snow — Create ServiceNow incident for a stored incident
// (goes through the connector layer, so any configured auth method works).
router.post('/incidents/:id/snow', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const incident = await CorrelatedIncident.findOne({ _id: req.params.id, userId });
    if (!incident) return res.status(404).json({ success: false, error: 'Not found' });

    const out = await orchestrator.createIncidentForCorrelation(userId, incident, { force: !!req.body?.force });
    res.json({ success: true, snowIncident: out.incident, alreadyExisted: out.alreadyExisted, assessment: out.assessment });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// GET /api/correlation/incidents/:id/assessment — does remediation need a change request?
router.get('/incidents/:id/assessment', protect, async (req, res) => {
  try {
    const incident = await CorrelatedIncident.findOne({ _id: req.params.id, userId: req.user._id.toString() });
    if (!incident) return res.status(404).json({ success: false, error: 'Not found' });
    res.json({ success: true, assessment: orchestrator.assessRemediation(incident) });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// POST /api/correlation/incidents/:id/change-request — raise a CR for the remediation
router.post('/incidents/:id/change-request', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const incident = await CorrelatedIncident.findOne({ _id: req.params.id, userId });
    if (!incident) return res.status(404).json({ success: false, error: 'Not found' });

    const out = await orchestrator.raiseChangeRequest(userId, incident, {
      plan: req.body?.plan, reason: req.body?.reason, riskLevel: req.body?.riskLevel, force: !!req.body?.force,
    });
    res.json({ success: true, changeRequest: out.changeRequest, alreadyExisted: out.alreadyExisted });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// POST /api/correlation/incidents/:id/process — incident + (if needed) change request
router.post('/incidents/:id/process', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const incident = await CorrelatedIncident.findOne({ _id: req.params.id, userId });
    if (!incident) return res.status(404).json({ success: false, error: 'Not found' });

    const result = await orchestrator.processCorrelation(userId, incident, {
      raiseChange: req.body?.raiseChange !== false,
    });
    res.json({ success: true, ...result });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// POST /api/correlation/auto-process — raise incidents/CRs for new correlations in bulk
router.post('/auto-process', protect, async (req, res) => {
  try {
    const results = await orchestrator.autoProcess(req.user._id.toString(), {
      minAlerts: req.body?.minAlerts ?? 2,
      onlyCritical: !!req.body?.onlyCritical,
    });
    res.json({ success: true, processed: results.length, results });
  } catch (error) {
    res.status(400).json({ success: false, error: error.message });
  }
});

// ---------------------------------------------------------------------------
// Cron Job Management
// ---------------------------------------------------------------------------

// POST /api/correlation/cron — Start a recurring correlation job
router.post('/cron', protect, async (req, res) => {
  try {
    const { intervalMinutes = 15, clusterId, hours = 48 } = req.body;
    const userId = req.user._id.toString();
    const token = req.headers.authorization?.replace('Bearer ', '');
    const cronKey = `${userId}:${clusterId || 'all'}`;

    // Clear existing job for this user/cluster
    if (cronJobs.has(cronKey)) {
      clearInterval(cronJobs.get(cronKey).intervalId);
      cronJobs.delete(cronKey);
    }

    const intervalMs = Math.max(5, parseInt(intervalMinutes)) * 60 * 1000;
    const cronJobId = crypto.randomUUID();

    const runJob = async () => {
      try {
        console.log(`[Cron ${cronJobId}] Running correlation for user=${userId} cluster=${clusterId || 'all'}`);
        const response = await axios.post(`${CORRELATION_URL}/api/correlate`, {
          userId, clusterId, token, hours: parseInt(hours),
        }, { timeout: 300000 });

        if (response.data.success && response.data.clusters?.length > 0) {
          await storeCorrelationResults(userId, response.data, clusterId, cronJobId);
          console.log(`[Cron ${cronJobId}] Stored ${response.data.clusters.length} clusters`);
        }
      } catch (err) {
        console.error(`[Cron ${cronJobId}] Error:`, err.message);
      }
    };

    // Run immediately, then on interval
    runJob();
    const intervalId = setInterval(runJob, intervalMs);

    cronJobs.set(cronKey, {
      intervalId,
      cronJobId,
      userId,
      clusterId: clusterId || 'all',
      intervalMinutes: parseInt(intervalMinutes),
      hours: parseInt(hours),
      startedAt: new Date(),
    });

    res.json({
      success: true,
      cronJobId,
      intervalMinutes: parseInt(intervalMinutes),
      message: `Correlation will run every ${intervalMinutes} minutes`,
    });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// DELETE /api/correlation/cron — Stop a recurring correlation job
router.delete('/cron', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const { clusterId } = req.query;
    const cronKey = `${userId}:${clusterId || 'all'}`;

    if (cronJobs.has(cronKey)) {
      clearInterval(cronJobs.get(cronKey).intervalId);
      cronJobs.delete(cronKey);
      return res.json({ success: true, message: 'Cron job stopped' });
    }

    res.json({ success: true, message: 'No active cron job found' });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// GET /api/correlation/cron — Get active cron job status
router.get('/cron', protect, async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const jobs = [];
    for (const [key, job] of cronJobs.entries()) {
      if (job.userId === userId) {
        jobs.push({
          cronJobId: job.cronJobId,
          clusterId: job.clusterId,
          intervalMinutes: job.intervalMinutes,
          hours: job.hours,
          startedAt: job.startedAt,
        });
      }
    }
    res.json({ success: true, jobs });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// POST /api/correlation/alerts — Correlate specific alerts
router.post('/alerts', protect, async (req, res) => {
  try {
    const { alertIds } = req.body;
    const userId = req.user._id.toString();
    const token = req.headers.authorization?.replace('Bearer ', '');
    if (!alertIds || !alertIds.length) return res.status(400).json({ success: false, error: 'alertIds is required' });

    const response = await axios.post(`${CORRELATION_URL}/api/correlate/alerts`, {
      userId, alertIds, token,
    }, { timeout: 120000 });
    res.json(response.data);
  } catch (error) {
    if (error.response) return res.status(error.response.status).json(error.response.data);
    res.status(503).json({ success: false, error: 'Correlation engine unavailable.' });
  }
});

// GET /api/correlation/health — Check engine status
router.get('/health', async (req, res) => {
  try {
    const response = await axios.get(`${CORRELATION_URL}/api/health`, { timeout: 5000 });
    res.json({ ...response.data, proxy: 'authService' });
  } catch (error) {
    res.status(503).json({ status: 'unavailable', error: error.message });
  }
});

module.exports = router;
