{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devopscopilot.secretName" . }}
  labels:
    {{- include "devopscopilot.labels" . | nindent 4 }}
    app.kubernetes.io/component: cluster-agent
type: Opaque
stringData:
  USER_ID: {{ .Values.secret.userId | quote }}
  CLUSTER_ID: {{ .Values.secret.clusterId | quote }}
  KAFKA_USERNAME: {{ .Values.secret.kafkaUsername | quote }}
  KAFKA_PASSWORD: {{ .Values.secret.kafkaPassword | quote }}
{{- end }}
